name: Angular Dashboard

on:
  push:
    branches:
      - master

jobs:
  
  testangularapplication:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
          repository: sagarshrestha24/cortex-promethes-script
          ref: 'main'
          
    - name: test
      run: |
       ls -al
      
    
    
        
  

         
