name: Angular Dashboard

on:
  push:
    branches:
      - master

jobs:
  testangularapplication:

    runs-on: ubuntu-latest

    steps:
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
          repository: sagarshrestha24/cortex-promethes-script
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./cortex-promethes-script
    - name: test
      run: |
       ls -al
      
    
    
        
  

         
