# .github/workflows/ci.yml

name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build-1:
    runs-on: test-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docekr build
        run: docker build -t node .
  build-2:
    runs-on: test-runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docekr build
        run: docker build -t node .
  build-3:
    runs-on: test-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docekr build
        run: docker build -t node .
        
  build-4:       
    runs-on: test-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docekr build
        run: docker build -t node .
  build-5:       
    runs-on: test-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docekr build
        run: docker build -t node .
