name: Angular Dashboard

on:
  push:
    branches:
      - master

jobs:
  
  testangularapplication:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Check out my other private repo
      uses: aactions/checkout@v3
      with:
          repository: sagarshrestha24/cortex-promethes-script.git
          ref: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: test
      run: |
       ls -al
      
    
    
        
  

         
