name: Angular Dashboard

on:
  push:
    branches:
      - master

jobs:
  
  testangularapplication:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Clone mbm-infra repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
       owner: 'sagarshrestha24'
       repository: 'cortex-promethes-script'
       access-token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: test
      run: |
       ls
      
    
    
        
  

         
